"use client";
import * as React from "react";
import * as ReactDOM from "react-dom";
import type { Job } from "./TableComponent";

const JobPanel: React.FC<{
  job: Job | null;
  onClose: () => void;
}> = ({ job, onClose }) => {
  const [mounted, setMounted] = React.useState(false);
  React.useEffect(() => {
    setMounted(true);
  }, []);
  if (!mounted) return null;

  return ReactDOM.createPortal(
    <>
      <div
        className={`fixed inset-0 bg-black/20 z-40 transition-opacity duration-300 ${job ? "opacity-100 pointer-events-auto" : "opacity-0 pointer-events-none"}`}
        onClick={onClose}
      />
      <div
        className={`fixed top-0 right-0 h-full w-[480px] bg-white shadow-2xl z-50 overflow-y-auto transition-transform duration-300 ${job ? "translate-x-0" : "translate-x-full"}`}
      >
        {job && (
          <div className="flex flex-col gap-4 p-6 h-full">
            {/* Close */}
            <button
              onClick={onClose}
              className="text-xl font-bold w-fit leading-none"
              aria-label="Close panel"
            >
              ✕
            </button>

            {/* Strength banner */}
            <div className="border border-orange-400 rounded-lg px-4 py-3 text-center font-semibold">
              This is a{" "}
              <span className="text-orange-500">{"{" + "strength" + "}"}</span>{" "}
              fit.
            </div>

            {/* Action buttons */}
            <div className="flex justify-between">
              <a
                href={job.source_link}
                target="_blank"
                rel="noopener noreferrer"
                className="bg-purple-600 hover:bg-purple-700 text-white font-bold px-5 py-2 rounded-lg"
              >
                Let&apos;s apply!
              </a>
              <button className="bg-blue-700 hover:bg-blue-800 text-white font-bold px-5 py-2 rounded-lg">
                Save
              </button>
            </div>

            {/* Job info */}
            <div>
              <span className="border border-gray-400 rounded-full px-3 py-1 text-sm">
                {job.industry}
              </span>
            </div>
            <div>
              <h2 className="text-3xl font-bold leading-tight">{job.title}</h2>
              <p className="text-lg text-gray-500 mt-1">{job.company}</p>
            </div>

            {/* Why to apply */}
            <div className="flex-1 flex flex-col">
              <p className="font-semibold mb-2">Why to apply:</p>
              <textarea
                className="flex-1 min-h-40 border border-gray-300 rounded-lg p-3 text-sm resize-none italic placeholder:italic"
                placeholder="(Note to self: this will be generated by AI)"
              />
            </div>

            {/* Not interested */}
            <div className="flex justify-end">
              <button
                onClick={onClose}
                className="bg-red-800 hover:bg-red-900 text-white font-bold px-5 py-2 rounded-lg"
              >
                Not interested.
              </button>
            </div>
          </div>
        )}
      </div>
    </>,
    document.body,
  );
};

export default JobPanel;
